site_name: 游尔桑的笔记们
site_description: Kyocius 的自救笔记
site_url: https://kyocius.github.io/notes/
copyright: Copyright &copy; 2024-2025 <a href="https://github.com/Kyocius">Kyocius</a>.
site_author: Kyocius

theme:
  name: material
  language: zh
  icon: 
    logo: material/notebook-outline

  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: brown
      accent: amber
      toggle:
        icon: material/lightbulb-on
        name: 切换至深色模式
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: 切换至浅色模式
  features:
      - content.code.copy
      - content.tooltips
      - navigation.tracking
      #- navigation.tabs
      - navigation.indexes
      - navigation.top


markdown_extensions:
  - meta
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 4

extra_javascript:
  - js/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - css/custom.css
  - css/headings.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

    